# shell.nix — Complete Android development environment.
#
# Enter with:
#   nix develop     (via flake.nix, pinned nixos-unstable — preferred)
#   nix-shell       (via <nixpkgs> from NIX_PATH)
#
# Provides: JDK 17, Gradle, and a full Android SDK — recent platforms,
# build-tools, platform-tools (adb/fastboot), cmdline-tools (sdkmanager),
# the NDK, and the emulator binary. System images are deliberately omitted
# here (they are API/ABI-specific and huge); the `emulator` devShell in
# flake.nix ships an AVD-ready system image instead.

{ pkgs ? import <nixpkgs> {
    config = {
      # Android SDK artifacts are marked "unfree" and additionally require an
      # explicit SDK license acceptance. Both must be set.
      allowUnfree = true;
      android_sdk.accept_license = true;
    };
  }
}:

let
  inherit (pkgs) lib;

  jdk = pkgs.jdk17;

  android = pkgs.androidenv.composeAndroidPackages {
    # Recent stable API levels (Android 14/15/16/17). "latest" = 37.1 today.
    platformVersions = [ "34" "35" "36" "latest" ];
    # Matching build-tools lines. "latest" = 37.0.0 today.
    buildToolsVersions = [ "34.0.0" "35.0.0" "36.1.0" "latest" ];

    includeEmulator = "if-supported";
    includeNDK = "if-supported";   # ~1 GB; set false if you never write C/C++ (JNI)
    includeSystemImages = false;  # system images live in the `emulator` shell
    includeSources = false;       # set true to browse framework sources
  };

  sdk = android.androidsdk;
in

pkgs.mkShell {
  name = "android-dev";

  packages = [
    sdk       # adb, fastboot, sdkmanager, avdmanager, emulator, aapt2, ...
    jdk
    pkgs.gradle
  ];

  LANG = "C.UTF-8";
  LC_ALL = "C.UTF-8";
  JAVA_HOME = jdk.home;

  ANDROID_HOME = "${sdk}/libexec/android-sdk";
  ANDROID_SDK_ROOT = "${sdk}/libexec/android-sdk";  # legacy alias
  ANDROID_NDK_ROOT = "${sdk}/libexec/android-sdk/ndk-bundle";

  shellHook = ''
    # NixOS is not FHS: point AGP at the store's patched aapt2 rather than the
    # one it would fetch from Maven. Pick the newest build-tools copy.
    aapt2_bin="$(ls -1v "$ANDROID_HOME"/build-tools/*/aapt2 2>/dev/null | tail -n1)"
    if [ -n "$aapt2_bin" ]; then
      export GRADLE_OPTS="-Dorg.gradle.project.android.aapt2FromMavenOverride=$aapt2_bin"
    fi

    # Expose the SDK's CMake for CLI use.
    cmake_root="$(echo "$ANDROID_HOME"/cmake/*/ 2>/dev/null)"
    if [ -n "$cmake_root" ]; then
      export PATH="$cmake_root/bin:$PATH"
    fi

    # Only write local.properties inside an actual Gradle Android project.
    if [ -e settings.gradle ] || [ -e settings.gradle.kts ] || [ -e build.gradle ] || [ -e build.gradle.kts ]; then
      if ! grep -q '^sdk.dir=' local.properties 2>/dev/null; then
        printf '# generated by nix-shell\nsdk.dir=%s\n' "$ANDROID_HOME" >> local.properties
      fi
    fi

    echo "Android SDK -> $ANDROID_HOME"
  '';
}
